### ISSUE TITLE
Beginning the Game

### ISSUE THREAD

**Issue by Triopticon** [Triopticon/IPND#2]
- [x] Immediately after running the program, user is prompted to select a difficulty level from easy / medium / hard. **Issue #5 Prompt user to select a difficulty level**
- [x] User did not choose the correct difficulty level #6
- [x] Welcome prompt #8 
- [x] Prompt user to enter a username #7 
- [x] Number of guesses per problem #9
- [x] Once a level is selected, game displays a fill-in-the-blank and a prompt to fill in the first blank.
      - Displays a fill-in-the-blank text #10
      - Prompt to fill in the first blank #11
